### PR TITLE
Windows support

### PR DESCRIPTION
**Pull request by kohenkatz**
This PR allows applications to run on Windows.

The application will not support graceful restart, since TableFlip doesn't have Windows support, but it is still adequate for users who use Windows machines for development and Linux for production.

It extracts the tableflip code into `internal/platform/reloader` with conditional compilation depending on which platform is being used.

I have not finished testing it yet, but I wanted to get it out here to see if you want any changes to it.

### CODE REVIEW

**Comment by sagikazarmark** [comment]
Interesting! Thanks for the PR.

TBH I never expected anyone to use this project on Windows. 😄 

My first instinct though is to raise this issue in the tableflip project to see whether they want to add windows support, or at least "make it work" on windows.

**Comment by kohenkatz** [comment]
I believe this has been discussed on the tableflip project several times in the past, and that they are not inclined to change it there.

Tableflip cannot run on Windows because Windows does not allow replacing a running executable with a new version, so there is no way to do the replacement without stopping the application anyway. Adding this to tableflip itself would therefore be pointless.

There are several reasons I think it is appropriate to do it here in this project:

1. The use-case for having it is specifically for those who develop and test locally on their own Windows desktop/laptop machines but run in production on Linux. That means this is a requirement for the application, not for the library itself. It also allows any developer who doesn't need this feature to simply delete the `_windows.go` file if they don't think they need it.
2. There are other cases in which an application developer might want OS-specific behavior. As a template for building Go applications, giving a best-practice example of how to implement such behavior seems to fit the goals of this project.

**Comment by sagikazarmark** [comment]
> The use-case for having it is specifically for those who develop and test locally on their own Windows desktop/laptop machines but run in production on Linux.

I think that's a perfectly valid reason to patch the behavior in the library itself.

I'm not trying to block this, because I think that problem addresses is perfectly valid, but I also think that solving this issue in the library itself would be much more valuable in other projects as well.

I understand that the _behavior_ cannot work on windows, but it would be nice if the library hadn't failed on Windows machines.

**Comment by sagikazarmark** [comment]
@kohenkatz dropped them a line, we will see 🙂 I hope you don't mind holding this off till they answer.

**Comment by kohenkatz** [comment]
I submitted a PR for tableflip. If/when it gets merged I will open a new PR here to add support again.

**Comment by sagikazarmark** [comment]
Awesome! Thanks!

**Pull request closed without merging**
